### ISSUE TITLE
Any chance to have it work in JSX

### ISSUE THREAD

**Issue by mike3run** [shmargum/vim-sass-colors#5]
For styled-components

https://www.styled-components.com

**Comment by shmargum** [comment]
I meant to reply to this sooner, but didn't want to have to say that this is out of scope for the project.

Unfortunately though I'd say this is not in the scope of this project, and probably belongs in another project related to JSX syntax (feel free to fork this or borrow any parts though)

The main reason is that this would have to load on and understand JS syntax.  There are also many other languages and flavors of languages that can include CSS and each one would need a different syntax parser, as well as perhaps different import logic.

I could potentially abstract out some of the common logic and create separate modules for different filetypes -- but this will definitely take some time, plus I am not too familiar with the other syntaxes :/

**Comment by mike3run** [comment]
No problem at all thanks for this plugin anyways!
